version: '3'
services:
  my-pay-mysql:
    image: mysql:8.0.32
    networks:
      - my-pay-network
    ports:
      - "3308:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=my_pay
      - MYSQL_USER=hongs
      - MYSQL_PASSWORD=1234
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  membership-service:
    image: my-pay-membership-service:0.0.1
    networks:
      - my-pay-network
    ports:
      - "8081:8080"
    depends_on:
      - my-pay-mysql
    #    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://my-pay-mysql:3306/my_pay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=hongs
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
#      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_OPEN-IN-VIEW=false
networks:
  my-pay-network:
    driver: bridge